title: GOMES SIX Gustavo
logo: /assets/img/photo2.png
description: Numéro de téléphone -> 06 27 18 85 24 E-mail -> gustavogomes.six@gmail.com [LinkedIn](https://www.linkedin.com/in/gustavo-gomes-six/)
#show_downloads: false
theme: jekyll-theme-minimal
